export const countryCodes = [
    { name: 'Mali', dial_code: '+223', code: 'ML', flag: '🇲🇱' },
    { name: 'Guinée', dial_code: '+224', code: 'GN', flag: '🇬🇳' },
    { name: 'Sénégal', dial_code: '+221', code: 'SN', flag: '🇸🇳' },
    { name: 'Côte d\'Ivoire', dial_code: '+225', code: 'CI', flag: '🇨🇮' },
    { name: 'Burkina Faso', dial_code: '+226', code: 'BF', flag: '🇧🇫' },
    { name: 'Niger', dial_code: '+227', code: 'NE', flag: '🇳🇪' },
    { name: 'Ghana', dial_code: '+233', code: 'GH', flag: '🇬🇭' },
    { name: 'France', dial_code: '+33', code: 'FR', flag: '🇫🇷' },
    { name: 'États-Unis', dial_code: '+1', code: 'US', flag: '🇺🇸' },
    { name: 'Algérie', dial_code: '+213', code: 'DZ', flag: '🇩🇿' },
    { name: 'Maroc', dial_code: '+212', code: 'MA', flag: '🇲🇦' },
    { name: 'Tunisie', dial_code: '+216', code: 'TN', flag: '🇹🇳' },
    { name: 'Bénin', dial_code: '+229', code: 'BJ', flag: '🇧🇯' },
    { name: 'Togo', dial_code: '+228', code: 'TG', flag: '🇹🇬' },
    { name: 'Cameroun', dial_code: '+237', code: 'CM', flag: '🇨🇲' },
    { name: 'Gabon', dial_code: '+241', code: 'GA', flag: '🇬🇦' },
    { name: 'Congo (Brazzaville)', dial_code: '+242', code: 'CG', flag: '🇨🇬' },
    { name: 'Congo (Kinshasa)', dial_code: '+243', code: 'CD', flag: '🇨🇩' },
];
